# ClusterRole for DORA system administrators
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-admin
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# ClusterRole for DORA operators
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-operator
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# ClusterRole for DORA developers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-developer
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
# ClusterRole for DORA monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-monitoring
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
# ServiceAccount for each namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-system-sa
  namespace: dora-system
  labels:
    app.kubernetes.io/part-of: dora-compliance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-agents-sa
  namespace: dora-agents
  labels:
    app.kubernetes.io/part-of: dora-compliance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-data-sa
  namespace: dora-data
  labels:
    app.kubernetes.io/part-of: dora-compliance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-monitoring-sa
  namespace: dora-monitoring
  labels:
    app.kubernetes.io/part-of: dora-compliance
---
# Role for agents to access config and secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-config-reader
  namespace: dora-agents
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
# Role for data namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-operator
  namespace: dora-data
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
# RoleBinding for agents
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-config-reader-binding
  namespace: dora-agents
  labels:
    app.kubernetes.io/part-of: dora-compliance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-config-reader
subjects:
- kind: ServiceAccount
  name: dora-agents-sa
  namespace: dora-agents
---
# RoleBinding for data operations
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-operator-binding
  namespace: dora-data
  labels:
    app.kubernetes.io/part-of: dora-compliance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-operator
subjects:
- kind: ServiceAccount
  name: dora-data-sa
  namespace: dora-data
---
# ClusterRoleBinding for monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dora-monitoring-binding
  labels:
    app.kubernetes.io/part-of: dora-compliance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dora-monitoring
subjects:
- kind: ServiceAccount
  name: dora-monitoring-sa
  namespace: dora-monitoring
---
# Pod Security Policy for restricted pods
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: dora-restricted
  labels:
    app.kubernetes.io/part-of: dora-compliance
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
# ClusterRole for using the restricted PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-restricted-psp-user
  labels:
    app.kubernetes.io/part-of: dora-compliance
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - dora-restricted
---
# Bind PSP to service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dora-restricted-psp-all-sa
  labels:
    app.kubernetes.io/part-of: dora-compliance
roleRef:
  kind: ClusterRole
  name: dora-restricted-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dora-system-sa
  namespace: dora-system
- kind: ServiceAccount
  name: dora-agents-sa
  namespace: dora-agents
- kind: ServiceAccount
  name: dora-data-sa
  namespace: dora-data 